name: Docs lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          directory: "site"

      - uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          files: "docs/**/*.md"
          files_ignore: "docs/reference/*.md"
          separator: ","

      - name: lint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd site
          ../scripts/pnpm_install.sh
          pnpm exec markdownlint-cli2 {{ steps.changed-files.outputs.all_changed_files }}
