# Filtering pull requests is much easier when we can reliably guarantee
# that the "Assignee" field is populated.
name: Docs markdown lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: tj-actions/changed-files@v45
      id: changed-files
      with:
        files: 'docs/**/*.md'
        separator: ","
    - uses: DavidAnson/markdownlint-cli2-action@v18
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ","
    - name: markdownlint-cli2-action
      uses: DavidAnson/markdownlint-cli2-action@v18.0.0
      with:
        config: ".github/actions/docs/markdownlint-cli2/.markdownlint.json"
        globs: "docs/**/*.md"
