name: Docs CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - uses: tj-actions/changed-files@bab30c2299617f6615ec02a68b9a40d10bd21366 # v45.0.5
        id: changed-files
        with:
          files: "docs/**/*.md"
          separator: ","

      - name: fmt
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pnpm exec markdown-table-formatter --check {{ steps.changed-files.outputs.all_changed_files }}

      - name: lint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pnpm exec markdownlint-cli2 {{ steps.changed-files.outputs.all_changed_files }}
